# Generated by Django 3.1 on 2023-03-27 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genreName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Жанр')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование фильма')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна')),
                ('producer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Продюссер')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('cover', models.CharField(blank=True, max_length=500, null=True, verbose_name='Обои')),
                ('poster', models.CharField(blank=True, max_length=500, null=True, verbose_name='Постер')),
                ('movieLink', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка на фильм')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinoApp.genres', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
    ]
