# Generated by Django 3.1 on 2023-03-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='isRec',
            field=models.BooleanField(blank=True, null=True, verbose_name='Рекомендовано'),
        ),
        migrations.AddField(
            model_name='movie',
            name='isTop',
            field=models.BooleanField(blank=True, null=True, verbose_name='Топ-10'),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Рейтинг'),
        ),
    ]
